//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Dataforest
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Table
	{
		private IEnumerable<DataObject> objects;

		private IEnumerable<Attribut> attributs;

		public virtual bool addAttribut(Attribut attr)
		{
			throw new System.NotImplementedException();
		}

		public virtual void deleteAttribut(Attribut attr)
		{
			throw new System.NotImplementedException();
		}

		public virtual bool addObject(DataObject obj)
		{
			throw new System.NotImplementedException();
		}

		public virtual void deleteObject(DataObject obj)
		{
			throw new System.NotImplementedException();
		}

		public virtual Attribut getAttribut(string name, int index)
		{
            int indx = 0;
            DataObject currentObjekt = objects.ElementAt(index);
            foreach (Attribut t in attributs)
            {
                if (t.Name == name)
                    break;
                else
                    indx++;
            }
           
            return currentObjekt.Data.ElementAt(indx);
            //  objects.ElementAt(index).Data.FirstOrDefault(attr => attr.Name == name);

			throw new System.NotImplementedException();
		}

		public virtual void setAttribut1(string name, int index, Attribut attr)
		{
			throw new System.NotImplementedException();
		}

	}
}

