//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Dataforest
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Table
	{
		private IEnumerable<Object> objects;

		private IEnumerable<Attribut> attributs;

		public virtual bool addAttribut(Attribut attr)
		{
			throw new System.NotImplementedException();
		}

		public virtual void deleteAttribut(Attribut attr)
		{
			throw new System.NotImplementedException();
		}

		public virtual bool addObject(Object obj)
		{
			throw new System.NotImplementedException();
		}

		public virtual void deleteObject(Object obj)
		{
			throw new System.NotImplementedException();
		}

		public virtual Attribut getAttribut(string name, object index)
		{
			throw new System.NotImplementedException();
		}

		public virtual void setAttribut1(string name, object index, Attribut attr)
		{
			throw new System.NotImplementedException();
		}

	}
}

