//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Dataforest
{
	using System;
    using System.Collections.Generic;
    using System.Data;
	using System.Linq;
	using System.Text;
    using System.Collections.ObjectModel;

	public class Tree
	{
		private Node startNode;

        private ObservableCollection<DataColumn> tabuList;

		public virtual Node StartNode
		{
            get
            {
                return startNode;
            }
            set
            {
                startNode = value;
            }
		}

		public virtual Collection<DataColumn> TabuList
		{
			get {
                return tabuList;   
            }
            set
            {
                tabuList = (ObservableCollection<DataColumn>)value;
            }
		}

		public virtual Table Table
		{
			get;
			set;
		}

		public Tree(DataRow row)
		{
		}

		public Tree(DataRow row, string column)
		{
		}

		public virtual void createOptimalTree()
		{
			throw new System.NotImplementedException();
		}

	}
}

