//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Dataforest
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Tree
	{
		private Node startNode;

		private IEnumerable<Attribut> tabuList;

		public virtual Node StartNode
		{
			get;
			set;
		}

		public virtual IEnumerable<Attribut> TabuList
		{
			get;
			set;
		}

		public virtual Table Table
		{
			get;
			set;
		}

		public Tree(object objs)
		{
		}

		public Tree(object objs, Attribut firstAttri)
		{
		}

		public virtual void createOptimalTree()
		{
			throw new System.NotImplementedException();
		}

	}
}

